# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/EOS/project/project_1/project_1.srcs/sources_1/bd/system/ip/system_switch_0/system_switch_0.xci
# IP: The module: 'system_switch_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EOS/project/project_1/project_1.gen/sources_1/bd/system/ip/system_switch_0/system_switch_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_switch_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EOS/project/project_1/project_1.gen/sources_1/bd/system/ip/system_switch_0/system_switch_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EOS/project/project_1/project_1.gen/sources_1/bd/system/ip/system_switch_0/system_switch_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/EOS/project/project_1/project_1.srcs/sources_1/bd/system/ip/system_switch_0/system_switch_0.xci
# IP: The module: 'system_switch_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EOS/project/project_1/project_1.gen/sources_1/bd/system/ip/system_switch_0/system_switch_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EOS/project/project_1/project_1.gen/sources_1/bd/system/ip/system_switch_0/system_switch_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EOS/project/project_1/project_1.gen/sources_1/bd/system/ip/system_switch_0/system_switch_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_switch_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
